security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager
            
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        main:
            pattern: ^/
            provider: main
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /Admin/Site/index
            logout:
                path: fos_user_security_logout
                target: /login
            remember_me:
                key: %secret%
            anonymous: true
            
     #c'est ici que tout se passe : qui a accés à quoi?
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Admin/, role: [ROLE_ADMIN, ROLE_USER]}
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_USER_ADMIN: [ROLE_ADMIN]
